## This script uses the UCI Human Activity Recognition Using Smartphones Dataset
##  as described at
##  http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones#
##  (retrieved 26 Jul 2014).
##  The script deals with the features data involving means and standard deviations.
##  It combines the training and test data, then finds the average of
##  the features of interest per subject, per activity.
##  The result is output into a file named "data/tidyAverages.txt"

if ( !file.exists("data") ) {
  dir.create( "data" )
}

## download and unzip data file if it doesn't already exist
destFileName <- "data/UCI-HAR-Dataset.zip"
if ( !file.exists(destFileName) ) {
  fileUrl <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
  download.file( fileUrl, destFileName, method = "curl" )
  ## record timestamp
  dateDownloaded <- format(Sys.time(), "%Y-%m-%d.%H:%M")
  write( dateDownloaded, file = "data/downloadTimestamp" )
  ## unzip
  unzip( destFileName, exdir = "data" )
}

filePathPrefix <- "data/UCI\ HAR\ Dataset/"
## read in features, convert them to valid column names,
##  and determine which ones are of interest (mean and standard deviation vals)
features <- read.table( paste( filePathPrefix, "features.txt", sep = "" )
                        , col.names = c( "index", "feature" ) )
features$stdNames <- make.names( features[,2] )
featureInterestInd <- ( grepl( "mean", features$stdNames, ignore.case = TRUE )
                        | grepl( "std", features$stdNames, ignore.case = TRUE )
)

## read in activity labels
activities <- read.table( paste( filePathPrefix, "activity_labels.txt", sep = "" )
                        , col.names = c( "id", "activity" ) )

## training data, using features as col names
trainSubj <- read.table( paste( filePathPrefix, "train/subject_train.txt", sep = "" )
                          )
trainRaw <- read.table( paste( filePathPrefix, "train/X_train.txt", sep = "" )
                   , col.names = features$stdNames )
trainAct <- read.table( paste( filePathPrefix, "train/y_train.txt", sep = "" )
                         )
## activity labels using factors as generated by the activity labels file data
trainAct$activity <- factor( trainAct$V1, levels = as.character(activities$id)
                            , labels = activities$activity)
## create data frame by binding subject, activity, 
##  and data involving mean and standard deviation
trainFull <- cbind( Subject = trainSubj$V1
                    , Activity = as.factor(trainAct$activity)
                    , trainRaw[, featureInterestInd]
                    )

## do similar with test data
testSubj <- read.table( paste( filePathPrefix, "test/subject_test.txt", sep = "" )
)
testRaw <- read.table( paste( filePathPrefix, "test/X_test.txt", sep = "" )
                     , col.names = features$stdNames )
testAct <- read.table( paste( filePathPrefix, "test/y_test.txt", sep = "" )
)
testAct$activity <- factor( testAct$V1, levels = as.character(activities$id)
                             , labels = activities$activity)
testFull <- cbind( Subject = testSubj$V1
                 , Activity = as.factor(testAct$activity)
                 , testRaw[, featureInterestInd]
                 )

## bind training and test data together
dataFull <- rbind( trainFull, testFull )

## split by subject and activity, then, for each chunk,
##  find means of the other columns
subjActSplit <- split( dataFull, list( dataFull$Subject, dataFull$Activity))
results <- vector( "list", length(subjActSplit) )
for ( i in seq_along( subjActSplit) ) {
  piece <- subjActSplit[[i]]
  summary <- as.list( colMeans( piece[,3:88] ) )
  subj <- piece[1,"Subject"]
  act <- piece[1,"Activity"]
  summary <- c( Subject = subj, Activity = act, summary )
  results[[i]] <- as.data.frame(summary)
}
## bind results into a dataframe
result <- do.call("rbind",results)
## re-add factor labels
result$Activity <- factor( result$Activity, levels = as.character(activities$id)
                             , labels = activities$activity)

## write results into file as a table
tidyFilename <- "data/tidyAverages.txt"
write.table( result, file = tidyFilename, row.names = FALSE )
